version: '3'
services:
    phpapp:
        build:
            context: ./
            dockerfile: Dockerfile
        image: phpapp:123
        ports:
            - "8080:80"
        volumes:
            - "./:/var/www/html"
        container_name: myphpapp-app
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '123123123'
            MYSQL_DATABASE: 'mydb'
            MYSQL_USER: 'denemeusr'
            MYSQL_PASSWORD: '123123'
        container_name: myphpapp-db
